name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - run: npm ci
    - run: npm run ci
    - run: npm run build
    - run: npm test
      env:
        CI: true
    - run: npm run bundle
